<a href="https://colab.research.google.com/github/sahilf2001/ML-DL-Projects/blob/main/Electrical_Energy_Output_of_a_Combined_CyclePowerPlant_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries


In [10]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [2]:
tf.__version__

'2.5.0'

Importing the Dataset

In [3]:
df = pd.read_excel('Folds5x2_pp.xlsx')
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [9]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print("Dependent Variables Vector:\n",X)
print("Independent Variable Vector:\n",y)

Dependent Variables Vector:
 [[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
Independent Variable Vector:
 [463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into Training and Test Sets

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu")) # using relu to remove the linear relation between input and hidden layers

Adding second hidden layer


In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Adding output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1)) # sigmoid used for binary classification
# soft max for multiclass classification

Compiling the ANN

In [19]:
# optimiser is the tool to perform stochastic gradient descent - through backpropagation
ann.compile(optimizer = 'adam',loss='mean_squared_error') #mse is for regression

Training the ANN on Training Set

In [23]:
ann.fit(X_train,y_train,batch_size = 32,epochs=100) # classic batch size is 32

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 27.2227
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 27.9832
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 27.6943
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 27.8809
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 26.5206
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7391
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 26.9815
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 27.3181
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 27.5898
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 27.1441
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 26.8766
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 27.1032
E

Predicting the result of Test Data

In [24]:
y_pred = ann.predict(X_test)

In [25]:
np.set_printoptions(precision=2)
y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)
z = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),axis=1)
print(z)

[[430.68 431.23]
 [461.07 460.01]
 [464.53 461.14]
 ...
 [471.94 473.26]
 [438.74 438.  ]
 [458.09 463.28]]


In [26]:
test_loss = ann.evaluate(X_test, y_test)
print(test_loss)

60/60 [==============================] - 0s 1ms/step - loss: 25.0479
25.047876358032227
